# Generated by Django 4.1 on 2022-10-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p1', models.FloatField(default=0)),
                ('p2', models.FloatField(default=0)),
                ('p3', models.FloatField(default=0)),
                ('p4', models.FloatField(default=0)),
                ('p5', models.FloatField(default=0)),
                ('p6', models.FloatField(default=0)),
                ('p7', models.FloatField(default=0)),
                ('p8', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mixer',
            name='p1',
            field=models.CharField(default='CaNO3', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p2',
            field=models.CharField(default='KNO3', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p3',
            field=models.CharField(default='NH4NO3', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p4',
            field=models.CharField(default='MgSO4', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p5',
            field=models.CharField(default='KH2PO4', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p6',
            field=models.CharField(default='K2SO4', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p7',
            field=models.CharField(default='Micro', max_length=1024),
        ),
        migrations.AddField(
            model_name='mixer',
            name='p8',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='MixerData',
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='mixer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixer.mixer'),
        ),
    ]
