# Generated by Django 4.1 on 2022-10-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0003_mixerhistory_s_mixerhistory_v1_mixerhistory_v2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixer',
            name='p8',
            field=models.CharField(default='B', max_length=1024),
        ),
    ]
