# Generated by Django 4.1 on 2022-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0004_alter_mixer_p8'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixer',
            name='z_p1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_p8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixer',
            name='z_v8',
            field=models.FloatField(default=0),
        ),
    ]
