# Generated by Django 4.1 on 2022-10-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_mixerhistory_mixer_p1_mixer_p2_mixer_p3_mixer_p4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixerhistory',
            name='s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mixerhistory',
            name='v8',
            field=models.FloatField(default=0),
        ),
    ]
